import { type CommunicationSymbol } from "../types";

export const layouts: CommunicationSymbol[][] = [
  [
    {
      id: "symbol_0",
      x: 100,
      y: 100,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
    {
      id: "symbol_1",
      x: 250,
      y: 100,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
  ],
  [
    {
      id: "symbol_0",
      x: 100,
      y: 100,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
    {
      id: "symbol_1",
      x: 250,
      y: 100,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
    {
      id: "symbol_2",
      x: 100,
      y: 250,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
    {
      id: "symbol_3",
      x: 250,
      y: 250,
      width: 100,
      height: 100,
      stroke: "black",
      strokeWidth: 1,
      rotation: 0,
      name: "symbol",
    },
  ],
];
